// frontend/src/components/Navbar.tsx
const Navbar = () => {
  return (
    <nav className="fixed top-0 left-0 w-full z-50 bg-transparent backdrop-blur-sm border-b border-white/5">
      <div className="max-w-7xl mx-auto flex items-center justify-between px-8 py-5">
        {/* Logo */}
        <div className="flex items-center gap-2">
          <div className="w-3 h-3 bg-blue-500/10 rounded-full blur-[2px] relative">
            <div className="absolute inset-0 bg-blue-400/60 rounded-full blur-sm"></div>
          </div>
          <h1 className="text-white text-xl font-semibold tracking-wide">
            Doom
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-400">
              Scroll
            </span>
          </h1>
        </div>

        {/* Right side - Links & Buttons */}
        <div className="flex items-center gap-8">
          {/* Nav Links */}
          <ul className="flex items-center gap-8 text-slate-400">
            <li className="hover:text-blue-400 transition-colors cursor-pointer">Home</li>
            <li className="hover:text-blue-400 transition-colors cursor-pointer">About</li>
          </ul>

          {/* Buttons */}
          <div className="flex items-center gap-4">
            <button className="px-5 py-2 bg-white/5 hover:bg-white/10 text-white border border-white/10 rounded-lg transition-colors">
              Sign In
            </button>
            <button className="px-5 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors">
              Sign Up
            </button>
          </div>
        </div>
      </div>
    </nav>
  );
};

export default Navbar;

// frontend/src/components/Navbar.svelte
<script lang="ts">
  import { writable } from 'svelte/store';
  let open = writable(false);

  function toggleMenu() {
    open.update(o => !o);
  }
</script>

<nav class="fixed w-full bg-lapis text-white flex justify-between items-center p-4 z-50 border-b-4 border-orange">
  <div class="text-2xl font-bold">DoomScroller</div>

  <ul class="hidden md:flex space-x-8">
    <li><a href="#section1" class="text-yellow hover:text-orange transition-colors">Stage 1</a></li>
    <li><a href="#section2" class="text-yellow hover:text-orange transition-colors">Stage 2</a></li>
    <li><a href="#section3" class="text-yellow hover:text-orange transition-colors">Stage 3</a></li>
  </ul>

  <!-- Mobile Burger -->
  <div class="md:hidden flex flex-col gap-1 cursor-pointer" on:click={toggleMenu}>
    <span class="w-6 h-0.5 bg-orange transition-transform" class:rotate-45={$open}></span>
    <span class="w-6 h-0.5 bg-orange transition-opacity" class:opacity-0={$open}></span>
    <span class="w-6 h-0.5 bg-orange transition-transform" class:-rotate-45={$open}></span>
  </div>

  <!-- Mobile Menu -->
  {#if $open}
    <ul class="absolute top-16 right-0 bg-lapis w-1/2 h-screen flex flex-col items-center justify-start pt-10 space-y-8 md:hidden transition-transform">
      <li><a href="#section1" on:click={() => open.set(false)} class="text-yellow hover:text-orange">Stage 1</a></li>
      <li><a href="#section2" on:click={() => open.set(false)} class="text-yellow hover:text-orange">Stage 2</a></li>
      <li><a href="#section3" on:click={() => open.set(false)} class="text-yellow hover:text-orange">Stage 3</a></li>
    </ul>
  {/if}
</nav>
